const RADARS = [
  { id:"RUDO", name:"Оренбург", lat:RADAR_COORDS.RUDO[0], lon:RADAR_COORDS.RUDO[1], range:250 },
  { id:"RUDP", name:"Петрозаводск", lat:RADAR_COORDS.RUDP[0], lon:RADAR_COORDS.RUDP[1], range:250 },
  { id:"RUTD", name:"Тамбов", lat:RADAR_COORDS.RUTD[0], lon:RADAR_COORDS.RUTD[1], range:250 },
  { id:"RUDX", name:"Архангельск", lat:RADAR_COORDS.RUDX[0], lon:RADAR_COORDS.RUDX[1], range:250 },
  { id:"RAVO", name:"Воейково", lat:RADAR_COORDS.RAVO[0], lon:RADAR_COORDS.RAVO[1], range:250 },
  { id:"RAKT", name:"Котлас", lat:RADAR_COORDS.RAKT[0], lon:RADAR_COORDS.RAKT[1], range:250 },
  { id:"RUDB", name:"Брянск", lat:RADAR_COORDS.RUDB[0], lon:RADAR_COORDS.RUDB[1], range:250 },
  { id:"RUDV", name:"Вологда", lat:RADAR_COORDS.RUDV[0], lon:RADAR_COORDS.RUDV[1], range:250 },
  { id:"RUDG", name:"Волгоград", lat:RADAR_COORDS.RUDG[0], lon:RADAR_COORDS.RUDG[1], range:250 },
  { id:"RATL", name:"Тула", lat:RADAR_COORDS.RATL[0], lon:RADAR_COORDS.RATL[1], range:250 },
  { id:"RAKD", name:"Краснодар", lat:RADAR_COORDS.RAKD[0], lon:RADAR_COORDS.RAKD[1], range:250 },
  { id:"RUDT", name:"Ставрополь", lat:RADAR_COORDS.RUDT[0], lon:RADAR_COORDS.RUDT[1], range:250 },
  { id:"RUWJ", name:"Валдай", lat:RADAR_COORDS.RUWJ[0], lon:RADAR_COORDS.RUWJ[1], range:250 },
  { id:"RAMI", name:"Миллерово", lat:RADAR_COORDS.RAMI[0], lon:RADAR_COORDS.RAMI[1], range:250 },
  { id:"RAVN", name:"Внуково", lat:RADAR_COORDS.RAVN[0], lon:RADAR_COORDS.RAVN[1], range:250 },
  { id:"RAKU", name:"Курск", lat:RADAR_COORDS.RAKU[0], lon:RADAR_COORDS.RAKU[1], range:250 },
  { id:"RUDI", name:"Ижевск", lat:RADAR_COORDS.RUDI[0], lon:RADAR_COORDS.RUDI[1], range:250 },
  { id:"RAYL", name:"Элиста", lat:RADAR_COORDS.RAYL[0], lon:RADAR_COORDS.RAYL[1], range:250 },
  { id:"RUDL", name:"Смоленск", lat:RADAR_COORDS.RUDL[0], lon:RADAR_COORDS.RUDL[1], range:250 },
  { id:"RASM", name:"Самара", lat:RADAR_COORDS.RASM[0], lon:RADAR_COORDS.RASM[1], range:250 },
  { id:"RABG", name:"Белгород", lat:RADAR_COORDS.RABG[0], lon:RADAR_COORDS.RABG[1], range:250 },
  { id:"RUDM", name:"Минеральные Воды", lat:RADAR_COORDS.RUDM[0], lon:RADAR_COORDS.RUDM[1], range:250 },
  { id:"RUDK", name:"Кострома", lat:RADAR_COORDS.RUDK[0], lon:RADAR_COORDS.RUDK[1], range:250 },
  { id:"RUDZ", name:"Казань", lat:RADAR_COORDS.RUDZ[0], lon:RADAR_COORDS.RUDZ[1], range:250 },
  { id:"RAVL", name:"Великие Луки", lat:RADAR_COORDS.RAVL[0], lon:RADAR_COORDS.RAVL[1], range:250 },
  { id:"RUDU", name:"Уфа", lat:RADAR_COORDS.RUDU[0], lon:RADAR_COORDS.RUDU[1], range:250 },
  { id:"RUDN", name:"Нижний Новгород", lat:RADAR_COORDS.RUDN[0], lon:RADAR_COORDS.RUDN[1], range:250 },
  { id:"RAKW", name:"Киров", lat:RADAR_COORDS.RAKW[0], lon:RADAR_COORDS.RAKW[1], range:250 }
];
